[gentoo]
priority = 9999
sync-uri = https://mirrors.kernel.org/gentoo/releases/amd64/binpackages/23.0/x86-64-v3/
location = /var/cache/binhost/gentoo-x86-64-v3
verify-signature = true

[gentoo-fallback]
priority = 9998
sync-uri = https://mirrors.kernel.org/gentoo/releases/amd64/binpackages/23.0/x86-64/
location = /var/cache/binhost/gentoo
verify-signature = true
