[env]
SHLVL = "0"

[font]
size = 13
builtin_box_drawing = true
normal = { family = "GeistMono NFM", style = "Medium" }
bold = { family = "GeistMono NFM", style = "Bold" }
italic = { family = "GeistMono NFM", style = "Italic" }
bold_italic = { family = "GeistMono NFM", style = "Bold Italic" }

[window]
opacity = 0.95
decorations = "None"

[window.padding]
x = 10
y = 10

[cursor.style]
shape = "Block"

[keyboard]
bindings = [
  { key = "Enter", mods = "Shift", chars = "\u000a" },
]

[scrolling]
history = 10000

[general]
import = ["~/.config/alacritty/cinder-grove.toml"]
