import = ["~/.config/alacritty/themes/gruvbox_dark.toml"]

[font]
size = 16

[font.normal]
family = "BerkeleyMono Nerd Font"

[window]
decorations = "none"
opacity = 0.95

[env]
WINIT_UNIX_BACKEND = "wayland"
