# Colors (Cinder Grove)
# Based on Ashen by Daniel Fichtinger
# License: MIT

# Default Colors
[colors.primary]
background = '#131210'
foreground = '#BBB3A9'

# Selection Colors
[colors.cursor]
cursor = '#DDD5CA'
text = '#131210'

# Normal Colors
[colors.normal]
black = '#131210'
red = '#B34A45'
green = '#879B5C'
yellow = '#D9A441'
blue = '#6785A1'
magenta = '#9A788F'
cyan = '#58918C'
white = '#ACA49B'

# Bright Colors
[colors.bright]
black = '#58534C'
red = '#B34A45'
green = '#879B5C'
yellow = '#D9A441'
blue = '#6785A1'
magenta = '#9A788F'
cyan = '#58918C'
white = '#DDD5CA'
