env SHLVL=0

font_family family="Iosevka Custom" style=Regular
bold_font family="Iosevka Custom" style=Heavy
italic_font family="Iosevka Custom" style=Italic
bold_italic_font family="Iosevka Custom" style="Bold Italic"
font_size 13

background_opacity 0.95
hide_window_decorations yes
window_padding_width 10
confirm_os_window_close 0

cursor_shape block
shell_integration no-cursor

scrollback_lines 10000

include cinder-grove.conf
