font_family      CommitMono Nerd Font Mono
font_size        13

tab_bar_style    hidden

hide_window_decorations titlebar-only
confirm_os_window_close 0
background_opacity 0.98
enable_audio_bell no
scrollback_lines 10000
window_padding_width 10

include ashen.conf
