font_family family="IosevkaTerm NFM" style=Regular
bold_font family="IosevkaTerm NFM" style=Bold
italic_font family="IosevkaTerm NFM" style=Italic
bold_italic_font family="IosevkaTerm NFM" style="Bold Italic"
font_size 13

background_opacity 0.95
hide_window_decorations yes
window_padding_width 2
confirm_os_window_close 0

cursor_shape block
shell_integration no-cursor

scrollback_lines 10000

include cinder-grove.conf
