;;; tsc-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from tsc.el

(register-definition-prefixes "tsc" '("tsc-"))


;;; Generated autoloads from tsc-dyn-get.el

(register-definition-prefixes "tsc-dyn-get" '("tsc-"))

;;; End of scraped data

(provide 'tsc-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; tsc-autoloads.el ends here
