local keymap = vim.keymap.set
local opts = { noremap = true, silent = true }

keymap("n", "<leader><space>", ":noh<CR>", opts)
keymap("n", "<leader>w", ":w<CR>", opts)
keymap("n", "<leader>q", ":q<CR>", opts)
keymap("n", "<C-h>", "<C-w>h", opts)
keymap("n", "<C-j>", "<C-w>j", opts)
keymap("n", "<C-k>", "<C-w>k", opts)
keymap("n", "<C-l>", "<C-w>l", opts)
keymap("n", "<leader>sv", ":vsplit<CR>", opts)
keymap("n", "<leader>sh", ":split<CR>", opts)
keymap("n", "j", "gj", opts)
keymap("n", "k", "gk", opts)
keymap("n", "Q", "<nop>", opts)

keymap("n", "<leader>ff", function()
  require("telescope.builtin").find_files()
end, opts)
keymap("n", "<leader>fg", function()
  require("telescope.builtin").live_grep()
end, opts)
keymap("n", "<leader>fb", function()
  require("telescope.builtin").buffers()
end, opts)
keymap("n", "<leader>ft", function()
  require("telescope.builtin").treesitter()
end, opts)

keymap("n", "<leader>e", ":NvimTreeToggle<CR>", opts)
keymap("n", "<leader>gs", ":Git<CR>", opts)

keymap("n", "gd", function()
  vim.lsp.buf.definition()
end, opts)
keymap("n", "gr", function()
  vim.lsp.buf.references()
end, opts)
keymap("n", "<leader>ca", function()
  vim.lsp.buf.code_action()
end, opts)
keymap("n", "<leader>rn", function()
  vim.lsp.buf.rename()
end, opts)
keymap("n", "K", function()
  vim.lsp.buf.hover()
end, opts)

keymap("n", "<leader>=", function()
  require("conform").format()
end, opts)
