[metadata]
name = "portage"
description = "Search Portage packages"
requirements = ["qsearch"]

[source]
command = "qsearch --all . --nocolor | sed 's/: /\\t/'"
display = "{split:\t:0}  {split:\t:1}"
output = "{split:\t:0}"

[preview]
command = "qsearch --all --nocolor '^{}$'"

[keybindings]
ctrl-i = "actions:install"
ctrl-u = "actions:unmerge"

[actions.install]
description = "Emerge selected package"
command = "sudo emerge --ask '{}'"
mode = "execute"

[actions.unmerge]
description = "Unmerge selected package"
command = "sudo emerge --ask --depclean '{}'"
mode = "execute"
