[metadata]
name = "portage"
description = "Search Portage packages"
requirements = ["eix"]

[source]
command = "eix --pure-packages --only-names '*'"

[preview]
command = "eix --verbose '{}'"

[keybindings]
enter = "actions:install"
ctrl-u = "actions:unmerge"

[actions.install]
description = "Emerge selected package"
command = "doas emerge --ask '{}'"
mode = "execute"

[actions.unmerge]
description = "Unmerge selected package"
command = "doas emerge --ask --unmerge '{}'"
mode = "execute"
