format = """
$directory\
$git_branch\
$git_state\
$git_status\
$conda\
$python\
$nodejs\
$cmd_duration\
$jobs\
$shlvl\
$status\
$line_break\
$character"""

scan_timeout = 30
command_timeout = 500
add_newline = true

[character]
success_symbol = "[❯](#4a8b8b)"
error_symbol = "[❯](#b14242)"

[directory]
truncation_length = 1
truncate_to_repo = false
style = "#d5d5d5 bold"
format = "[$path]($style)[$read_only]($read_only_style) "

[line_break]
disabled = false

[git_branch]
symbol = ""
style = "#d87c4a"
format = "on [$symbol$branch]($style) "

[git_status]
style = "#e49a44"
format = '([\[$all_status$ahead_behind\]]($style) )'
conflicted = "=${count} "
ahead = "⇡${count} "
behind = "⇣${count} "
diverged = "⇕⇡${ahead_count}⇣${behind_count} "
untracked = "?${count} "
stashed = "\\$${count} "
modified = "!${count} "
staged = "+${count} "
renamed = "»${count} "
deleted = "✘${count} "

[git_state]
style = "#e5a72a"
format = '\([$state( $progress_current/$progress_total)]($style)\) '

[cmd_duration]
min_time = 2_000
style = "#e49a44"
format = "[$duration]($style) "
show_milliseconds = false

[status]
style = "#b14242"
format = "[$status]($style) "
disabled = false
pipestatus = true
pipestatus_separator = "|"
pipestatus_format = '\[$pipestatus\] => [$status]($style) '

[username]
style_user = "#e5a72a bold"
style_root = "#b14242 bold"
format = "[$user]($style) "
show_always = false
ssh_only = true

[hostname]
style = "#e5a72a"
format = "at [$hostname]($style) "
ssh_only = true

[shlvl]
threshold = 2
style = "#949494"
format = "[$shlvl]($style) "
disabled = false

[jobs]
style = "#e5a72a"
format = "[$symbol$number]($style) "
symbol = "✦ "
threshold = 1

[python]
style = "#e49a44"
format = '[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style) '
symbol = ""

[nodejs]
style = "#4a8b8b"
format = "[$symbol($version)]($style) "
symbol = ""

[conda]
style = "#c4693d"
format = "[$symbol$environment]($style) "
symbol = ""
ignore_base = true
