{-# LANGUAGE ForeignFunctionInterface #-}

module HeldDictation (initializeDictation, startDictation, releaseDictation, cancelDictation) where

import Control.Exception (catch, finally, try, IOException)
import Control.Monad (unless)
import Data.Bits (testBit)
import Data.Monoid (All (All))
import Data.Word (Word8)
import Foreign (Ptr, allocaBytes, peekElemOff)
import Foreign.C.Types (CChar, CInt (CInt))
import Graphics.X11.Xlib.Types (Display (Display))
import System.IO (Handle, hClose, hFlush, hPutStrLn)
import System.Process (createProcess, proc, CreateProcess (std_in, close_fds), StdStream (CreatePipe))
import XMonad
import qualified XMonad.Util.ExtensibleState as XS

data HeldDictation = HeldDictation Bool (Maybe Handle)

instance ExtensionClass HeldDictation where
  initialValue = HeldDictation False Nothing

initializeDictation :: X ()
initializeDictation = withDisplay $ \display -> do
  f9 <- io $ keysymToKeycode display xK_F9
  isHeld <- io $ keyIsPressed display f9
  XS.put $ HeldDictation isHeld Nothing

startDictation :: X ()
startDictation = do
  HeldDictation isHeld worker <- XS.get
  unless isHeld $ do
    XS.put $ HeldDictation True worker
    result <- io $ try $ createProcess (proc "voxtype-hold" [])
      {std_in = CreatePipe, close_fds = True}
    case result of
      Left errorMessage -> trace $ show (errorMessage :: IOException)
      Right (Just input, _, _, _) -> XS.put $ HeldDictation True (Just input)
      Right _ -> pure ()

releaseDictation :: Event -> X All
releaseDictation KeyEvent {ev_event_type = eventType, ev_keycode = code}
  | eventType == keyRelease = withDisplay $ \display -> do
      f9 <- io $ keysymToKeycode display xK_F9
      if code /= f9 then pure (All True) else do
        -- XQueryKeymap ignores the synthetic releases generated by key repeat.
        isPressed <- io $ keyIsPressed display code
        unless isPressed $ do
          HeldDictation _ worker <- XS.get
          io $ case worker of
            Nothing -> pure ()
            Just input -> ignoreIO $
              (hPutStrLn input "release" >> hFlush input) `finally` hClose input
          XS.put $ HeldDictation False Nothing
        pure (All True)
releaseDictation _ = pure (All True)

cancelDictation :: X ()
cancelDictation = do
  HeldDictation isHeld worker <- XS.get
  io $ case worker of
    Nothing -> pure ()
    Just input -> ignoreIO $ hClose input
  XS.put $ HeldDictation isHeld Nothing

ignoreIO :: IO () -> IO ()
ignoreIO action = action `catch` ignore
  where
    ignore :: IOException -> IO ()
    ignore _ = pure ()

foreign import ccall unsafe "XQueryKeymap"
  xQueryKeymap :: Display -> Ptr CChar -> IO CInt

keyIsPressed :: Display -> KeyCode -> IO Bool
keyIsPressed display code = allocaBytes 32 $ \pressed -> do
  _ <- xQueryKeymap display pressed
  byte <- peekElemOff pressed (fromIntegral code `div` 8)
  pure $ testBit (fromIntegral byte :: Word8) (fromIntegral code `mod` 8)
