-- Cinder Grove
-- Based on Ashen by Daniel Fichtinger

vim.cmd('highlight clear')
if vim.fn.exists('syntax_on') == 1 then
  vim.cmd('syntax reset')
end

vim.o.background = 'dark'
vim.o.termguicolors = true
vim.g.colors_name = 'cinder-grove'

local c = {
  bg = '#121212',
  bg_alt = '#191919',
  surface = '#212121',
  muted = '#535353',
  gray = '#949494',
  fg_dim = '#A7A7A7',
  fg = '#B4B4B4',
  fg_bright = '#D5D5D5',
  red = '#B14242',
  green = '#8A9A5B',
  yellow = '#E5A72A',
  blue = '#6284A3',
  magenta = '#95799A',
  cyan = '#4A8B8B',
  orange = '#C4693D',
}

local groups = {
  Normal = { fg = c.fg, bg = 'NONE' },
  NormalNC = { fg = c.fg, bg = 'NONE' },
  NormalFloat = { fg = c.fg, bg = c.bg_alt },
  FloatBorder = { fg = c.blue, bg = c.bg_alt },
  FloatTitle = { fg = c.fg_bright, bg = c.bg_alt, bold = true },
  Cursor = { fg = c.bg, bg = c.fg_bright },
  CursorIM = { link = 'Cursor' },
  CursorColumn = { bg = c.surface },
  CursorLine = { bg = c.surface },
  CursorLineNr = { fg = c.yellow, bg = c.surface, bold = true },
  LineNr = { fg = c.muted },
  SignColumn = { bg = 'NONE' },
  ColorColumn = { bg = c.surface },
  Visual = { bg = c.muted },
  VisualNOS = { bg = c.muted },
  Search = { fg = c.bg, bg = c.yellow },
  IncSearch = { fg = c.bg, bg = c.blue, bold = true },
  CurSearch = { link = 'IncSearch' },
  Substitute = { fg = c.bg, bg = c.magenta },
  MatchParen = { fg = c.yellow, bold = true, underline = true },
  Pmenu = { fg = c.fg, bg = c.bg_alt },
  PmenuSel = { fg = c.fg_bright, bg = c.muted },
  PmenuSbar = { bg = c.surface },
  PmenuThumb = { bg = c.muted },
  PmenuMatch = { fg = c.blue, bg = c.bg_alt, bold = true },
  PmenuMatchSel = { fg = c.yellow, bg = c.muted, bold = true },
  StatusLine = { fg = c.fg_bright, bg = c.muted },
  StatusLineNC = { fg = c.gray, bg = c.surface },
  TabLine = { fg = c.fg, bg = c.surface },
  TabLineFill = { bg = c.bg_alt },
  TabLineSel = { fg = c.fg_bright, bg = c.muted, bold = true },
  WinSeparator = { fg = c.muted },
  VertSplit = { link = 'WinSeparator' },
  Folded = { fg = c.gray, bg = c.surface },
  FoldColumn = { fg = c.muted },
  QuickFixLine = { bg = c.surface, bold = true },
  Directory = { fg = c.blue },
  Title = { fg = c.magenta, bold = true },
  Question = { fg = c.green },
  MoreMsg = { fg = c.cyan },
  ModeMsg = { fg = c.fg_dim, bold = true },
  WarningMsg = { fg = c.yellow },
  ErrorMsg = { fg = c.red, bold = true },
  NonText = { fg = c.muted },
  EndOfBuffer = { fg = c.muted },
  SpecialKey = { fg = c.muted },
  Whitespace = { fg = c.muted },
  WildMenu = { fg = c.bg, bg = c.yellow },
  SpellBad = { undercurl = true, sp = c.red },
  SpellCap = { undercurl = true, sp = c.blue },
  SpellLocal = { undercurl = true, sp = c.cyan },
  SpellRare = { undercurl = true, sp = c.magenta },

  Comment = { fg = c.muted, italic = true },
  Constant = { fg = c.cyan },
  String = { fg = c.green },
  Character = { fg = c.green },
  Number = { fg = c.cyan },
  Boolean = { fg = c.cyan },
  Float = { fg = c.cyan },
  Identifier = { fg = c.fg },
  Function = { fg = c.fg_bright, bold = true },
  Statement = { fg = c.magenta },
  Conditional = { fg = c.magenta },
  Repeat = { fg = c.magenta },
  Label = { fg = c.magenta },
  Operator = { fg = c.orange },
  Keyword = { fg = c.magenta },
  Exception = { fg = c.magenta },
  PreProc = { fg = c.magenta },
  Include = { fg = c.magenta },
  Define = { fg = c.magenta },
  Macro = { fg = c.magenta },
  Type = { fg = c.cyan, italic = true },
  StorageClass = { fg = c.magenta },
  Structure = { fg = c.cyan, italic = true },
  Typedef = { fg = c.cyan, italic = true },
  Special = { fg = c.blue },
  SpecialChar = { fg = c.yellow },
  Tag = { fg = c.blue, italic = true },
  Delimiter = { fg = c.blue },
  SpecialComment = { fg = c.gray, italic = true },
  Debug = { fg = c.red },
  Underlined = { fg = c.blue, underline = true },
  Ignore = { fg = c.muted },
  Error = { fg = c.red, bold = true },
  Todo = { fg = c.yellow, bold = true },
  Added = { fg = c.green },
  Changed = { fg = c.cyan },
  Removed = { fg = c.red },

  DiffAdd = { fg = c.green, bg = c.surface },
  DiffChange = { fg = c.cyan, bg = c.surface },
  DiffDelete = { fg = c.red, bg = c.surface },
  DiffText = { fg = c.yellow, bg = c.muted, bold = true },
  DiagnosticError = { fg = c.red },
  DiagnosticWarn = { fg = c.yellow },
  DiagnosticInfo = { fg = c.blue },
  DiagnosticHint = { fg = c.cyan },
  DiagnosticOk = { fg = c.green },
  DiagnosticUnderlineError = { undercurl = true, sp = c.red },
  DiagnosticUnderlineWarn = { undercurl = true, sp = c.yellow },
  DiagnosticUnderlineInfo = { undercurl = true, sp = c.blue },
  DiagnosticUnderlineHint = { undercurl = true, sp = c.cyan },
  DiagnosticUnderlineOk = { undercurl = true, sp = c.green },
  DiagnosticSignError = { link = 'DiagnosticError' },
  DiagnosticSignWarn = { link = 'DiagnosticWarn' },
  DiagnosticSignInfo = { link = 'DiagnosticInfo' },
  DiagnosticSignHint = { link = 'DiagnosticHint' },
  DiagnosticSignOk = { link = 'DiagnosticOk' },

  ['@variable'] = { fg = c.fg },
  ['@variable.builtin'] = { fg = c.cyan, italic = true },
  ['@variable.parameter'] = { fg = c.blue, italic = true },
  ['@variable.member'] = { fg = c.fg_bright },
  ['@constant'] = { fg = c.cyan },
  ['@constant.builtin'] = { fg = c.cyan },
  ['@module'] = { fg = c.blue, bold = true },
  ['@label'] = { fg = c.magenta },
  ['@string'] = { fg = c.green },
  ['@string.escape'] = { fg = c.fg_bright },
  ['@character'] = { fg = c.green },
  ['@character.special'] = { fg = c.fg_bright },
  ['@boolean'] = { fg = c.cyan },
  ['@number'] = { fg = c.cyan },
  ['@type'] = { fg = c.cyan, italic = true },
  ['@type.builtin'] = { fg = c.cyan },
  ['@property'] = { fg = c.fg_bright },
  ['@attribute'] = { fg = c.magenta },
  ['@function'] = { fg = c.fg_bright, bold = true },
  ['@function.builtin'] = { fg = c.fg_bright, bold = true },
  ['@function.call'] = { fg = c.fg_bright, bold = true },
  ['@function.macro'] = { fg = c.magenta },
  ['@constructor'] = { fg = c.fg_bright, italic = true },
  ['@operator'] = { fg = c.orange },
  ['@keyword'] = { fg = c.magenta },
  ['@keyword.operator'] = { fg = c.magenta },
  ['@punctuation'] = { fg = c.blue },
  ['@punctuation.bracket'] = { fg = c.muted },
  ['@punctuation.delimiter'] = { fg = c.blue },
  ['@punctuation.special'] = { fg = c.yellow },
  ['@comment'] = { link = 'Comment' },
  ['@markup.heading'] = { fg = c.green, bold = true },
  ['@markup.link'] = { fg = c.green, underline = true },
  ['@markup.link.url'] = { fg = c.blue, underline = true },
  ['@markup.raw'] = { fg = c.fg_bright, bg = c.bg_alt },
  ['@markup.list'] = { fg = c.orange },
  ['@markup.quote'] = { fg = c.yellow },
  ['@diff.plus'] = { fg = c.green },
  ['@diff.delta'] = { fg = c.cyan },
  ['@diff.minus'] = { fg = c.red },

  markdownHeadingDelimiter = { fg = c.green, bold = true },
  markdownCode = { fg = c.fg_bright, bg = c.bg_alt },
  markdownCodeBlock = { fg = c.fg_bright, bg = c.bg_alt },
  markdownLinkText = { fg = c.green, underline = true },
  markdownUrl = { fg = c.blue, underline = true },
  markdownListMarker = { fg = c.orange },
  markdownBlockquote = { fg = c.yellow },
  IblIndent = { fg = c.surface },
  IblScope = { fg = c.blue },
  GitSignsAdd = { fg = c.green },
  GitSignsChange = { fg = c.cyan },
  GitSignsDelete = { fg = c.red },
}

for group, spec in pairs(groups) do
  vim.api.nvim_set_hl(0, group, spec)
end

local terminal = {
  c.bg,
  c.red,
  c.green,
  c.yellow,
  c.blue,
  c.magenta,
  c.cyan,
  c.fg_dim,
  c.muted,
  c.red,
  c.green,
  c.yellow,
  c.blue,
  c.magenta,
  c.cyan,
  c.fg_bright,
}

for index, color in ipairs(terminal) do
  vim.g['terminal_color_' .. (index - 1)] = color
end
