#!/bin/sh

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

export PATH="$HOME/.local/bin:$HOME/.cargo/bin:$HOME/.bun/bin:/usr/local/bin:$PATH"
export XDG_CURRENT_DESKTOP="WM"
export XCURSOR_SIZE=48
export EDITOR=nvim
export TERMINAL=wezterm

xrdb -merge ~/.Xresources &
xset r rate 300 40 &

picom -b &
dunst &
feh --bg-fill ~/Pictures/wallpaper.jpg &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
blueman-applet &
solaar &

dwmblocks &

exec dbus-run-session dwm
