#!/bin/sh

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

export PATH="$HOME/.local/bin:$HOME/.cargo/bin:$HOME/.bun/bin:/usr/local/bin:$PATH"
export XDG_CURRENT_DESKTOP="WM"
export XCURSOR_SIZE=48
export TERMINAL=wezterm
export EDITOR="emacsclient -c -n"
export VISUAL=$EDITOR
export SUDO_EDITOR=vim
export MANPAGER="bat -plman"
export SSH_AUTH_SOCK="$HOME/.1password/agent.sock"
export GPG_TTY=$(tty)

xrdb -merge ~/.Xresources &
xset s on
xset s 600 0
xset +dpms
xset dpms 0 0 900
xset r rate 270 45
xss-lock --transfer-sleep-lock -- betterlockscreen -l dimpixel &

exec dbus-run-session -- sh -c '
picom -b &
dunst &
feh --bg-fill "$HOME/Pictures/wallpaper.jpg" &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
blueman-applet &
solaar &
emacs --daemon &

dwm &
dwm_pid=$!

dwmblocks &

wait $dwm_pid
'
