theme = "theme"

[editor]
line-number = "relative"
mouse = true
scrolloff = 8
popup-border = "all"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
