theme = "rose_pine"

[editor]
line-number = "relative"
mouse = true
scrolloff = 8
rulers = [80]
popup-border = "all"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.normal]
esc = ["collapse_section", "keep_primary_selection"]
