mode = "dark"

accent = "#E17A3F"
selection = "#58534C"
selection_foreground = "#DDD5CA"
selection_background = "#58534C"
muted = "#58534C"

background = "#131210"
dark_background = "#0F0E0D"
darker_background = "#0B0A09"
lighter_background = "#23201C"

foreground = "#BBB3A9"
dark_foreground = "#58534C"
light_foreground = "#ACA49B"
bright_foreground = "#DDD5CA"

hyprland_active_border = "rgba(e17a3fee) rgba(879b5cee) 45deg"
hyprland_inactive_border = "rgba(58534caa)"

red = "#B34A45"
yellow = "#D9A441"
orange = "#E17A3F"
green = "#879B5C"
cyan = "#58918C"
blue = "#6785A1"
magenta = "#9A788F"
brown = "#6F4B35"

bright_red = "#B34A45"
bright_yellow = "#D9A441"
bright_green = "#879B5C"
bright_cyan = "#58918C"
bright_blue = "#6785A1"
bright_magenta = "#9A788F"
