mode = "dark"

accent = "#E17A3F"
selection = "#58534C"
selection_foreground = "#DDD5CA"
selection_background = "#58534C"
muted = "#58534C"

background = "#131210"
dark_background = "#1B1916"
darker_background = "#131210"
lighter_background = "#23201C"

foreground = "#BBB3A9"
dark_foreground = "#58534C"
light_foreground = "#ACA49B"
bright_foreground = "#DDD5CA"

hyprland_active_border = "#E17A3F"
hyprland_inactive_border = "rgba(58534caa)"

red = "#B34A45"
yellow = "#D9A441"
orange = "#E17A3F"
green = "#879B5C"
cyan = "#58918C"
blue = "#6785A1"
magenta = "#9A788F"

bright_red = "#B34A45"
bright_yellow = "#D9A441"
bright_green = "#879B5C"
bright_cyan = "#58918C"
bright_blue = "#6785A1"
bright_magenta = "#9A788F"
