Section "InputClass"
	Identifier "pointers"
	MatchIsPointer "on"
	Driver "libinput"
	Option "AccelProfile" "flat"
EndSection

Section "InputClass"
	Identifier "touchpad"
	MatchIsTouchpad "on"
	Driver "libinput"
	Option "Tapping" "on"
	Option "TappingDragLock" "on"
	Option "DisableWhileTyping" "on"
EndSection
