theme[main_bg]="#0A0908"
theme[main_fg]="#ECE5DE"
theme[title]="#ECE5DE"
theme[hi_fg]="#DFD1CC"
theme[selected_bg]="#2D2924"
theme[selected_fg]="#ECE5DE"
theme[inactive_fg]="#AA9F95"
theme[proc_misc]="#C8C0B8"
theme[div_line]="#A17869"
theme[meter_bg]="#2D2924"
theme[graph_text]="#AA9F95"

theme[process_start]="#C8C0B8"
theme[process_mid]="#ECE5DE"
theme[process_end]="#ECE5DE"

theme[cpu_box]="#A17869"
theme[mem_box]="#A17869"
theme[net_box]="#A17869"
theme[proc_box]="#A17869"

theme[temp_start]="#C8C0B8"
theme[temp_mid]="#C5ABA2"
theme[temp_end]="#AC887B"

theme[cpu_start]="#A17869"
theme[cpu_mid]="#B8988D"
theme[cpu_end]="#DFD1CC"

theme[free_start]="#A17869"
theme[free_mid]="#B8988D"
theme[free_end]="#DFD1CC"

# Also used for the GPU power readout.
theme[cached_start]="#A17869"
theme[cached_mid]="#B8988D"
theme[cached_end]="#DFD1CC"

theme[available_start]="#A17869"
theme[available_mid]="#B8988D"
theme[available_end]="#DFD1CC"

theme[used_start]="#A17869"
theme[used_mid]="#B8988D"
theme[used_end]="#DFD1CC"

theme[download_start]="#A17869"
theme[download_mid]="#B8988D"
theme[download_end]="#DFD1CC"

theme[upload_start]="#A17869"
theme[upload_mid]="#B8988D"
theme[upload_end]="#DFD1CC"
