theme[main_bg]="#080503"
theme[main_fg]="#F1EAE5"
theme[title]="#F1EAE5"
theme[hi_fg]="#D1C0B6"
theme[selected_bg]="#725F52"
theme[selected_fg]="#F1EAE5"
theme[inactive_fg]="#A2968E"
theme[proc_misc]="#DED6D0"
theme[div_line]="#B39887"
theme[meter_bg]="#342C26"
theme[graph_text]="#342C26"

theme[process_start]="#DED6D0"
theme[process_mid]="#F1EAE5"
theme[process_end]="#F1EAE5"

theme[cpu_box]="#B39887"
theme[mem_box]="#B39887"
theme[net_box]="#B39887"
theme[proc_box]="#B39887"

theme[temp_start]="#C6BBB5"
theme[temp_mid]="#C69E58"
theme[temp_end]="#E07972"

theme[cpu_start]="#80756E"
theme[cpu_mid]="#B39887"
theme[cpu_end]="#F1EAE5"

theme[free_start]="#80756E"
theme[free_mid]="#B39887"
theme[free_end]="#F1EAE5"

# Also used for the GPU power readout.
theme[cached_start]="#A2968E"
theme[cached_mid]="#B39887"
theme[cached_end]="#F1EAE5"

theme[available_start]="#80756E"
theme[available_mid]="#B39887"
theme[available_end]="#F1EAE5"

theme[used_start]="#80756E"
theme[used_mid]="#B39887"
theme[used_end]="#F1EAE5"

theme[download_start]="#80756E"
theme[download_mid]="#B39887"
theme[download_end]="#F1EAE5"

theme[upload_start]="#80756E"
theme[upload_mid]="#B39887"
theme[upload_end]="#F1EAE5"
