# These settings were set by the catalyst build script that automatically
# built this stage.
# Please consult /usr/share/portage/config/make.conf.example for a more
# detailed example.
COMMON_FLAGS="-march=znver5 -O2 -pipe"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"
RUSTFLAGS="${RUSTFLAGS} -C target-cpu=znver5"

# This sets the language of build output to English.
# Please keep this setting intact when reporting bugs.
LC_MESSAGES=C.UTF-8
L10N="en en-US"

MAKEOPTS="-j24 -l25"
USE="wayland pipewire bluetooth dist-kernel"
FEATURES="getbinpkg"

GENTOO_MIRRORS="http://www.gtlib.gatech.edu/pub/gentoo \
    https://mirrors.kernel.org/gentoo/ \
    https://mirror.rackspace.com/gentoo/"

ACCEPT_LICENSE="-* @FREE @BINARY-REDISTRIBUTABLE"
