FEATURES="${FEATURES} getbinpkg binpkg-request-signature"
RUSTFLAGS="${RUSTFLAGS} -C target-cpu=native"
COMMON_FLAGS="-march=x86-64-v3 -O2 -pipe"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"

LC_MESSAGES=C.UTF-8
L10N="en en-US"

MAKEOPTS="-j16 -l17"
USE="dist-kernel wayland"

GENTOO_MIRRORS="http://www.gtlib.gatech.edu/pub/gentoo \
    https://mirrors.kernel.org/gentoo/ \
    https://mirror.rackspace.com/gentoo/"

ACCEPT_LICENSE="-* @FREE @BINARY-REDISTRIBUTABLE @EULA"
