gpu-api=vulkan
hwdec=nvdec
osc=no
osd-color=#BBB3A9
osd-font=IosevkaTerm Nerd Font
osd-outline-color=#131210
osd-selected-color=#E17A3F
osd-selected-outline-color=#131210
vo=gpu-next
vulkan-device=NVIDIA GeForce RTX 5070
