gpu-api=vulkan
hwdec=vulkan
osc=no
osd-color="#C5AFA4"
osd-font=IosevkaTerm Nerd Font
osd-outline-color="#15110F"
osd-selected-color="#F1A278"
osd-selected-outline-color="#15110F"
vo=gpu-next
vulkan-device=NVIDIA GeForce RTX 5070
