gpu-api=vulkan
hwdec=vulkan
osc=no
osd-color="#c5afa4"
osd-font=IosevkaTerm Nerd Font
osd-outline-color="#15110f"
osd-selected-color="#f1a278"
osd-selected-outline-color="#15110f"
vo=gpu-next
vulkan-device=NVIDIA GeForce RTX 5070
