
backend = "glx";
vsync = true;
xrender-sync-fence = true;

shadow = true;
shadow-radius = 14;
shadow-offset-x = -7;
shadow-offset-y = -7;
shadow-opacity = 0.4;
shadow-exclude = [
  "_NET_WM_WINDOW_TYPE@d:c:a = '_NET_WM_WINDOW_TYPE_DOCK'",
  "_NET_WM_WINDOW_TYPE@d:c:a = '_NET_WM_WINDOW_TYPE_DESKTOP'",
];

fading = false;

inactive-opacity = 0.95;
active-opacity = 1.0;
opacity-rule = [
  "100:class_g = 'mpv'",
];

corner-radius = 0;

blur: {
  method = "dual_kawase";
  strength = 5;
}
blur-background-exclude = [
  "_NET_WM_WINDOW_TYPE@d:c:a = '_NET_WM_WINDOW_TYPE_DOCK'",
  "_NET_WM_WINDOW_TYPE@d:c:a = '_NET_WM_WINDOW_TYPE_DESKTOP'",
  "class_g = 'slop'",
];
