backend = "glx";
vsync = false;
xrender-sync-fence = true;
use-damage = true;

shadow = true;
shadow-radius = 8;
shadow-offset-x = -7;
shadow-offset-y = -7;
shadow-opacity = 0.4;
shadow-exclude = [
  "window_type = 'dock'",
  "window_type = 'desktop'",
  "window_type = 'menu'",
  "window_type = 'dropdown_menu'",
  "window_type = 'popup_menu'",
  "window_type = 'tooltip'",
  "window_type = 'utility'",
  "window_type = 'combo'",
  "window_type = 'notification'",
  "override_redirect = true",
];

inactive-opacity = 0.95;
active-opacity = 1.0;

blur: {
  method = "dual_kawase";
  strength = 8;
}
blur-background-exclude = [
  "window_type = 'dock'",
  "window_type = 'desktop'",
  "window_type = 'menu'",
  "window_type = 'dropdown_menu'",
  "window_type = 'popup_menu'",
  "window_type = 'tooltip'",
  "window_type = 'utility'",
  "window_type = 'combo'",
  "window_type = 'notification'",
  "override_redirect = true",
  "class_g = 'slop'",
];
