#!/bin/bash
# Statusbar module: CPU usage
# Left click: show CPU details notification
# Right click: open btop

case $BUTTON in
1)
	cpu=$(top -bn1 | grep "Cpu(s)" | awk '{print int($2 + $4)}')
	notify-send "󰻠 CPU Usage" "Current CPU: $cpu%"
	;;
3)
	wezterm start --class btop-floating -- btop
	;;
esac

cpu=$(top -bn1 | grep "Cpu(s)" | awk '{print int($2 + $4)}')

if [ "$cpu" -ge 80 ]; then
	color="#b14242"
elif [ "$cpu" -ge 50 ]; then
	color="#e49a44"
else
	color="#a7a7a7"
fi

printf "^c%s^󰻠 %s%%^d^" "$color" "$cpu"
