#!/bin/bash
# Statusbar module: memory usage
# Left click: open btop
# Right click: show memory details notification

case $BUTTON in
	1)
		wezterm start --class btop-floating -- btop
		;;
	3)
		mem=$(free -h | awk '/Mem:/ {print $3 "/" $2}')
		swap=$(free -h | awk '/Swap:/ {print $3 "/" $2}')
		notify-send "󰍛 Memory Usage" "RAM: $mem\nSwap: $swap"
		;;
esac

mem=$(free | awk '/Mem:/ {printf "%.0f", $3/$2 * 100}')

if [ "$mem" -ge 80 ]; then
	color="#b14242"
elif [ "$mem" -ge 50 ]; then
	color="#e49a44"
else
	color="#a7a7a7"
fi

printf "^c%s^󰍛 %s%%^d^" "$color" "$mem"
