#!/bin/bash
# Statusbar module: volume control
# Left click: toggle mute
# Scroll up: volume up
# Scroll down: volume down
# Right click: show volume notification

case $BUTTON in
	1)
		pamixer -t
		;;
	4)
		pamixer -i 5
		;;
	5)
		pamixer -d 5
		;;
	3)
		notify-send "󰕿 Volume Control" "Left click: Toggle mute\nScroll up/down: Adjust volume"
		exit 0
		;;
esac

vol=$(pamixer --get-volume 2>/dev/null)
muted=$(pamixer --get-mute 2>/dev/null)

if [ "$muted" = "true" ]; then
	icon="󰝟"
	color="#535353"
	printf "^c%s^%s^d^" "$color" "$icon"
elif [ -z "$vol" ]; then
	exit 0
elif [ "$vol" -eq 0 ]; then
	icon="󰕿"
	color="#535353"

elif [ "$vol" -lt 30 ]; then
	icon="󰕿"
	color="#a7a7a7"

elif [ "$vol" -lt 70 ]; then
	icon="󰖀"
	color="#a7a7a7"

else
	icon="󰕾"
	color="#d87c4a"

fi

printf "^c%s^%s %s%%^d^" "$color" "$icon" "$vol"
