general {
    hide_cursor = true
    immediate_render = true
    fail_timeout = 2000
}

auth {
    pam:enabled = true
    pam:module = hyprlock
}

animations {
    enabled = true
}

background {
    monitor =
    color = rgba(19, 18, 16, 1.0)
}

label {
    monitor =
    text = $TIME
    color = rgba(221, 213, 202, 1.0)
    font_size = 72
    font_family = AdwaitaMono Nerd Font Mono
    position = 0, 120
    halign = center
    valign = center
}

label {
    monitor =
    text = $USER
    color = rgba(172, 164, 155, 1.0)
    font_size = 16
    font_family = AdwaitaMono Nerd Font Mono
    position = 0, 48
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 320, 54
    outline_thickness = 2
    dots_size = 0.22
    dots_spacing = 0.3
    dots_center = true
    outer_color = rgba(225, 122, 63, 0.9)
    inner_color = rgba(27, 25, 22, 0.92)
    font_color = rgba(221, 213, 202, 1.0)
    fade_on_empty = false
    placeholder_text = <span foreground="##ACA49B">Password</span>
    fail_text = <span foreground="##B34A45">$FAIL <b>($ATTEMPTS)</b></span>
    check_color = rgba(217, 164, 65, 1.0)
    fail_color = rgba(179, 74, 69, 1.0)
    capslock_color = rgba(154, 120, 143, 1.0)
    position = 0, -38
    halign = center
    valign = center
}
