shadow = true;
fading = true;
fade-in-step = 0.05;
fade-out-step = 0.05;
inactive-dim = 0.05;
corner-radius = 3;
dropdown_menu = { shadow = false; };
popup_menu    = { shadow = false; };
utility       = { shadow = false; };
