#!/usr/bin/env bash

mmsg watch all-clients | jq --unbuffered -c '
  .clients[] | select(
    .appid == "zen" and 
    (.title | type == "string") and 
    (.title | startswith("Extension: (Bitwarden")) and 
    .is_floating == false
  )' | while read -r match; do
    win_id=$(echo "$match" | jq -r '.id')
    mmsg dispatch togglefloating client,"$win_id"
    mmsg dispatch resizewin,450,650 client,"$win_id"
    mmsg dispatch centerwin client,"$win_id"
done
