state_file = "auto"
engine = "parakeet"

[hotkey]
enabled = false

[audio]
device = "default"
sample_rate = 16000
max_duration_secs = 60
pause_media = true

[parakeet]
model = "parakeet-tdt-0.6b-v3"
language = "en"
translate = false

[output]
mode = "type"
fallback_to_clipboard = true
type_delay_ms = 1

[output.notification]
on_recording_start = false
on_recording_stop = false
on_transcription = false

[osd]
top_margin = 0.6
