hover_effect_color=#A17869
middle_buttons_color=#C8C0B8
osc_color=#0A0908
playpause_color=#C8C0B8
seek_handle_color=#A17869
seekbarfg_color=#A17869
side_buttons_color=#C8C0B8
time_color=#C8C0B8
title_color=#C8C0B8
