hover_effect_color=#B39887
middle_buttons_color=#DED6D0
osc_color=#080503
playpause_color=#DED6D0
seek_handle_color=#B39887
seekbarfg_color=#B39887
side_buttons_color=#DED6D0
time_color=#C6BBB5
title_color=#DED6D0
