hover_effect_color=#f1a278
middle_buttons_color=#c5afa4
osc_color=#15110f
playpause_color=#c5afa4
seek_handle_color=#f1a278
seekbarfg_color=#f1a278
side_buttons_color=#c5afa4
time_color=#c5afa4
title_color=#e9d1c5
