hover_effect_color=#F09361
middle_buttons_color=#C9AEA0
osc_color=#16110F
playpause_color=#C9AEA0
seek_handle_color=#F09361
seekbarfg_color=#F09361
side_buttons_color=#C9AEA0
time_color=#C9AEA0
title_color=#ECCFC1
