hover_effect_color=#F1A278
middle_buttons_color=#C5AFA4
osc_color=#15110F
playpause_color=#C5AFA4
seek_handle_color=#F1A278
seekbarfg_color=#F1A278
side_buttons_color=#C5AFA4
time_color=#C5AFA4
title_color=#E9D1C5
