local refactor = require('refactoring')
local debug = require('refactoring.debug')

local map = vim.keymap.set

map({ 'n', 'x' }, '<leader>re', function()
  return refactor.extract_func()
end, { desc = 'Extract function', expr = true })
map({ 'n', 'x' }, '<leader>rE', function()
  return refactor.extract_func_to_file()
end, { desc = 'Extract function to file', expr = true })
map({ 'n', 'x' }, '<leader>rv', function()
  return refactor.extract_var()
end, { desc = 'Extract variable', expr = true })
map({ 'n', 'x' }, '<leader>ri', function()
  return refactor.inline_var()
end, { desc = 'Inline variable', expr = true })
map({ 'n', 'x' }, '<leader>rI', function()
  return refactor.inline_func()
end, { desc = 'Inline function', expr = true })
map({ 'n', 'x' }, '<leader>rs', function()
  refactor.select_refactor()
end, { desc = 'Select refactor' })

map({ 'n', 'x' }, '<leader>pv', function()
  return debug.print_var({ output_location = 'below' }) .. 'iw'
end, { desc = 'Print var below', expr = true })
map({ 'n', 'x' }, '<leader>pV', function()
  return debug.print_var({ output_location = 'above' }) .. 'iw'
end, { desc = 'Print var above', expr = true })
map({ 'n', 'x' }, '<leader>pe', function()
  return debug.print_exp({ output_location = 'below' })
end, { desc = 'Print expression below', expr = true })
map({ 'n', 'x' }, '<leader>pE', function()
  return debug.print_exp({ output_location = 'above' })
end, { desc = 'Print expression above', expr = true })
map('n', '<leader>pp', function()
  return debug.print_loc({ output_location = 'below' })
end, { desc = 'Print location below', expr = true })
map('n', '<leader>pP', function()
  return debug.print_loc({ output_location = 'above' })
end, { desc = 'Print location above', expr = true })
map('n', '<leader>pc', function()
  return debug.cleanup()
end, { desc = 'Clean debug prints', expr = true, remap = true })
