#!/usr/bin/env bash

eval "$(gnome-keyring-daemon --start --components=secrets,ssh,pkcs11)"
export GNOME_KEYRING_CONTROL
export SSH_AUTH_SOCK
export DESKTOP_SESSION=river
export XDG_CURRENT_DESKTOP=river

dbus-update-activation-environment --systemd --all
systemctl --user import-environment

killall -q xdg-desktop-portal-wlr
killall -q xdg-desktop-portal
killall -q waybar
killall -q dunst
killall -q nm-applet
killall -q blueman-applet
killall -q swaybg
killall -q swayidle

/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
/usr/lib/xdg-desktop-portal-wlr -r &
/usr/lib/xdg-desktop-portal -r &

waybar &
dunst &
nm-applet &
blueman-applet &

swaybg -m fill -i ~/Pictures/Wallpapers/diamond.jpg &
swayidle -w \
	timeout 900 "swaylock -f -i $HOME/Pictures/Wallpapers/diamond.jpg" \
	timeout 1800 "systemctl suspend" \
	before-sleep "swaylock -f -i $HOME/Pictures/Wallpapers/diamond.jpg"

wlr-randr --output DP-2 --mode 2560x1440@165.080Hz &
xrdb -merge "$HOME/.Xresources" &
gsettings set org.gnome.desktop.default-applications.terminal exec ghostty.desktop

gnome_schema="org.gnome.desktop.interface"
gsettings set "$gnome_schema" gtk-theme "Gruvbox-Dark"
gsettings set "$gnome_schema" icon-theme "Gruvbox-Plus-Dark"
gsettings set "$gnome_schema" cursor-theme "S1mple-Gruvbox-Dark"
gsettings set "$gnome_schema" font-name "Adwaita Sans 11"

riverctl xcursor-theme "Simp1e-Gruvbox-Dark"
riverctl input "pointer-1133-50503-Logitech_USB_Receiver" accel-profile flat
riverctl set-repeat 50 250
riverctl focus-follows-cursor normal
riverctl set-layout-gaps outer 4
riverctl set-layout-gaps inner 4
riverctl border-width 2
riverctl border-color-focused 0x83a598
riverctl border-color-unfocused 0x928374
riverctl declare-mode "passthrough"
riverctl default-layout rivertile
rivertile -view-padding 4 -outer-padding 4 -main-ratio 0.5 &

riverctl rule-add -app-id "thunar" -title "Rename*" float
riverctl rule-add -app-id "thunar" -title "File Operation Progress" float
riverctl rule-add -app-id "thunar" ssd
riverctl rule-add -app-id "solaar" ssd
riverctl rule-add -app-id "org.gnome.DejaDup" ssd
riverctl rule-add -app-id "com.mitchellh.ghostty" ssd
riverctl rule-add -app-id "org.gnome.Calendar" ssd
riverctl rule-add -app-id "qalculate-gtk" float
riverctl rule-add -app-id "pavucontrol-qt" float
riverctl rule-add -app-id "nm-connection-editor" float
riverctl rule-add -app-id "blueman-manager" float
riverctl rule-add -app-id "org.pulseaudio.pavucontrol" float
riverctl rule-add -app-id "flameshot" float
riverctl rule-add -app-id "xdg-desktop-portal-gtk" float

riverctl map normal Super+Shift C spawn "$HOME/.config/river/init"
riverctl map normal Super Q close
riverctl map normal Super F toggle-fullscreen
riverctl map normal Super Return spawn ghostty
riverctl map normal Super W spawn chromium
riverctl map normal Super E spawn thunar
riverctl map normal Super+Shift X spawn wlogout
riverctl map normal Super space spawn "rofi -show drun"
riverctl map normal Super U spawn "rofi -show emoji"
riverctl map normal Super Escape spawn "swaylock -f -i $HOME/Pictures/Wallpapers/diamond.jpg"
riverctl map normal None Print spawn '$HOME/.config/river/scripts/screenshot.sh -s -c'
riverctl map normal Super Print spawn '$HOME/.config/river/scripts/screenshot.sh -f -b'
riverctl map normal Super+Shift Print spawn '$HOME/.config/river/scripts/screenshot.sh -s -b'
riverctl map normal Super R spawn '$HOME/.config/river/scripts/record.sh'

for i in $(seq 1 9); do
	tags=$((1 << ($i - 1)))
	riverctl map normal Super $i set-focused-tags $tags
	riverctl map normal Super+Shift $i set-view-tags $tags
	riverctl map normal Super+Control $i toggle-focused-tags $tags
	riverctl map normal Super+Shift+Control $i toggle-view-tags $tags
done

riverctl map-pointer normal Super BTN_LEFT move-view
riverctl map-pointer normal Super BTN_RIGHT resize-view
riverctl map normal Super J focus-view next
riverctl map normal Super K focus-view previous
riverctl map normal Super+Control H send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal Super+Control L send-layout-cmd rivertile "main-ratio +0.05"
riverctl map normal Super+Shift J swap next
riverctl map normal Super+Shift K swap previous
riverctl map normal Super+Shift Space toggle-float

for mode in normal locked; do
	riverctl map $mode None XF86AudioRaiseVolume spawn "pamixer -i 5"
	riverctl map $mode None XF86AudioLowerVolume spawn "pamixer -d 5"
	riverctl map $mode None XF86AudioMute spawn "pamixer --toggle-mute"
	riverctl map $mode None XF86AudioMedia spawn "playerctl play-pause"
	riverctl map $mode None XF86AudioPlay spawn "playerctl play-pause"
	riverctl map $mode None XF86AudioPrev spawn "playerctl previous"
	riverctl map $mode None XF86AudioNext spawn "playerctl next"
done
