[general]
import = ["~/.config/alacritty/themes/muted-russet.toml"]

[window]
padding = { x = 8, y = 8 }
decorations = "None"

[font]
normal = { family = "IosevkaTerm Nerd Font", style = "Regular" }
size = 15

[cursor]
style = { shape = "Block", blinking = "On" }
