vim.cmd.highlight("clear")
vim.o.background = "dark"
vim.g.colors_name = "muted-russet"

local palette = {
  background = "#0A0908",
  container = "#171412",
  surface = "#23201C",
  overlay = "#2D2924",
  border = "#8E8071",
  muted = "#AA9F95",
  subtle = "#AA9F95",
  secondary = "#C8C0B8",
  text = "#C8C0B8",
  bright = "#ECE5DE",
  primary = "#A17869",
  ui_accent = "#B8988D",
  tertiary = "#C5ABA2",
  quaternary = "#DFD1CC",
  selection = "#2D2924",
  error = "#AC887B",
  warning = "#C5ABA2",
  success = "#B8988D",
  info = "#D2BEB7",
}

local groups = {
  Normal = { fg = palette.text, bg = palette.background },
  NormalNC = { link = "Normal" },
  NormalFloat = { fg = palette.text, bg = palette.overlay },
  FloatBorder = { fg = palette.border, bg = palette.overlay },
  FloatTitle = { fg = palette.ui_accent, bg = palette.overlay, bold = true },
  Cursor = { fg = palette.background, bg = palette.bright },
  CursorLine = { bg = palette.container },
  CursorColumn = { link = "CursorLine" },
  ColorColumn = { bg = palette.surface },
  LineNr = { fg = palette.muted },
  CursorLineNr = { fg = palette.primary, bold = true },
  SignColumn = { bg = palette.background },
  FoldColumn = { fg = palette.muted, bg = palette.background },
  Folded = { fg = palette.secondary, bg = palette.container },
  WinSeparator = { fg = palette.border },
  StatusLine = { fg = palette.text, bg = palette.surface },
  StatusLineNC = { fg = palette.muted, bg = palette.container },
  TabLine = { fg = palette.secondary, bg = palette.container },
  TabLineFill = { bg = palette.container },
  TabLineSel = { fg = palette.bright, bg = palette.selection, bold = true },
  Pmenu = { fg = palette.text, bg = palette.overlay },
  PmenuSel = { fg = palette.bright, bg = palette.selection },
  PmenuMatch = { fg = palette.ui_accent, bold = true },
  PmenuMatchSel = { fg = palette.bright, bg = palette.selection, bold = true },
  PmenuSbar = { bg = palette.surface },
  PmenuThumb = { bg = palette.border },
  Visual = { fg = palette.bright, bg = palette.selection },
  VisualNOS = { link = "Visual" },
  Search = { link = "Visual" },
  IncSearch = { fg = palette.bright, bg = palette.selection, bold = true },
  CurSearch = { link = "IncSearch" },
  Yank = { link = "Visual" },
  MatchParen = { fg = palette.bright, bg = palette.surface, bold = true, underline = true },
  NonText = { fg = palette.muted },
  SpecialKey = { link = "NonText" },
  Whitespace = { link = "NonText" },
  EndOfBuffer = { fg = palette.border },
  Directory = { fg = palette.tertiary },
  Title = { fg = palette.primary, bold = true },
  Comment = { fg = palette.muted, italic = true },
  Identifier = { fg = palette.text },
  Constant = { fg = palette.text },
  String = { link = "Constant" },
  Number = { link = "Constant" },
  Boolean = { link = "Constant" },
  Character = { link = "Constant" },
  Float = { link = "Constant" },
  Function = { fg = palette.text },
  Statement = { fg = palette.primary },
  Keyword = { link = "Statement" },
  PreProc = { link = "Statement" },
  Type = { fg = palette.text },
  Special = { fg = palette.text },
  Delimiter = { link = "Special" },
  Operator = { link = "Special" },
  Underlined = { fg = palette.primary, underline = true },
  Todo = { fg = palette.warning, bold = true },
  Error = { fg = palette.error },
  ErrorMsg = { link = "Error" },
  WarningMsg = { fg = palette.warning },
  MoreMsg = { fg = palette.primary },
  Question = { fg = palette.primary },
  WildMenu = { link = "PmenuSel" },
  DiffAdd = { fg = palette.success, bg = palette.container },
  DiffDelete = { fg = palette.error, bg = palette.container },
  DiffChange = { fg = palette.warning, bg = palette.container },
  DiffText = { fg = palette.bright, bg = palette.selection, bold = true },
  Added = { fg = palette.success },
  Removed = { fg = palette.error },
  Changed = { fg = palette.warning },
  DiagnosticError = { fg = palette.error },
  DiagnosticWarn = { fg = palette.warning },
  DiagnosticInfo = { fg = palette.info },
  DiagnosticHint = { fg = palette.secondary },
  DiagnosticOk = { fg = palette.success },
  DiagnosticUnderlineError = { sp = palette.error, undercurl = true },
  DiagnosticUnderlineWarn = { sp = palette.warning, undercurl = true },
  DiagnosticUnderlineInfo = { sp = palette.info, undercurl = true },
  DiagnosticUnderlineHint = { sp = palette.secondary, undercurl = true },
  DiagnosticDeprecated = { fg = palette.muted, strikethrough = true },
  DiagnosticUnnecessary = { fg = palette.muted },
  LspReferenceText = { bg = palette.surface, underline = true },
  LspReferenceRead = { link = "LspReferenceText" },
  LspReferenceWrite = { link = "LspReferenceText" },
  LspInlayHint = { fg = palette.muted, bg = palette.container },
  SpellBad = { sp = palette.error, undercurl = true },
  SpellCap = { sp = palette.warning, undercurl = true },
  SpellLocal = { sp = palette.info, undercurl = true },
  SpellRare = { sp = palette.secondary, undercurl = true },
  ["@variable"] = { link = "Identifier" },
  ["@variable.builtin"] = { link = "Identifier" },
  ["@variable.parameter"] = { link = "Identifier" },
  ["@variable.member"] = { link = "Identifier" },
  ["@module"] = { link = "Type" },
  ["@type"] = { link = "Type" },
  ["@function"] = { link = "Function" },
  ["@function.builtin"] = { link = "Function" },
  ["@constructor"] = { link = "Type" },
  ["@keyword"] = { link = "Statement" },
  ["@constant"] = { link = "Constant" },
  ["@string"] = { link = "String" },
  ["@number"] = { link = "Number" },
  ["@boolean"] = { link = "Boolean" },
  ["@property"] = { link = "Identifier" },
  ["@punctuation"] = { link = "Delimiter" },
  ["@operator"] = { link = "Operator" },
  ["@comment"] = { link = "Comment" },
  ["@lsp.type.variable"] = { link = "Identifier" },
  ["@lsp.type.parameter"] = { link = "Identifier" },
  ["@lsp.type.property"] = { link = "Identifier" },
  ["@lsp.type.function"] = { link = "Function" },
  ["@lsp.type.method"] = { link = "Function" },
  ["@lsp.type.type"] = { link = "Type" },
  ["@lsp.type.class"] = { link = "Type" },
  ["@lsp.type.enum"] = { link = "Type" },
  ["@lsp.type.enumMember"] = { link = "Constant" },
  ["@lsp.type.string"] = { link = "String" },
  ["@lsp.type.number"] = { link = "Number" },
  ["@lsp.type.keyword"] = { link = "Keyword" },
  ["@lsp.type.operator"] = { link = "Operator" },
  ["@lsp.mod.defaultLibrary"] = { fg = palette.text },
  ["@comment.error"] = { link = "DiagnosticError" },
  ["@comment.warning"] = { link = "DiagnosticWarn" },
  ["@comment.todo"] = { link = "Todo" },
  ["@comment.note"] = { link = "DiagnosticInfo" },
  ["@tag"] = { link = "Identifier" },
  ["@tag.attribute"] = { link = "Identifier" },
  ["@tag.delimiter"] = { link = "Delimiter" },
  ["@markup.heading"] = { link = "Title" },
  ["@markup.link"] = { link = "Underlined" },
  ["@markup.raw"] = { link = "String" },
  ["@markup.list"] = { link = "Delimiter" },
  ["@markup.strong"] = { bold = true },
  ["@markup.italic"] = { italic = true },
}

for name, attributes in pairs(groups) do
  vim.api.nvim_set_hl(0, name, attributes)
end

local ansi = {
  "#1A1715", "#956F6B", "#788578", "#928569",
  "#74818B", "#85778A", "#6F8782", "#C8C0B8",
  "#655F5A", "#AD807A", "#8C998B", "#A99A7A",
  "#87949E", "#998A9E", "#829A94", "#ECE5DE",
}

for index, color in ipairs(ansi) do
  vim.g["terminal_color_" .. (index - 1)] = color
end
