vim.cmd.highlight("clear")
vim.o.background = "dark"
vim.g.colors_name = "muted-umber"

local palette = {
  background = "#080503",
  container = "#140E0A",
  surface = "#221B17",
  overlay = "#342C26",
  border = "#80756E",
  muted = "#A2968E",
  subtle = "#B4A8A1",
  secondary = "#C6BBB5",
  text = "#DED6D0",
  bright = "#F1EAE5",
  primary = "#B39887",
  tertiary = "#C1AD9F",
  quaternary = "#D1C0B6",
  selection = "#725F52",
  error = "#E07972",
  warning = "#C69E58",
  success = "#78AA79",
  info = "#6DA1CD",
}

local groups = {
  Normal = { fg = palette.text, bg = palette.background },
  NormalNC = { link = "Normal" },
  NormalFloat = { fg = palette.text, bg = palette.overlay },
  FloatBorder = { fg = palette.border, bg = palette.overlay },
  FloatTitle = { fg = palette.primary, bg = palette.overlay, bold = true },
  Cursor = { fg = palette.background, bg = palette.bright },
  CursorLine = { bg = palette.container },
  CursorColumn = { link = "CursorLine" },
  ColorColumn = { bg = palette.surface },
  LineNr = { fg = palette.muted },
  CursorLineNr = { fg = palette.primary, bold = true },
  SignColumn = { bg = palette.background },
  FoldColumn = { fg = palette.muted, bg = palette.background },
  Folded = { fg = palette.secondary, bg = palette.container },
  WinSeparator = { fg = palette.border },
  StatusLine = { fg = palette.text, bg = palette.surface },
  StatusLineNC = { fg = palette.muted, bg = palette.container },
  TabLine = { fg = palette.secondary, bg = palette.container },
  TabLineFill = { bg = palette.container },
  TabLineSel = { fg = palette.bright, bg = palette.selection, bold = true },
  Pmenu = { fg = palette.text, bg = palette.overlay },
  PmenuSel = { fg = palette.bright, bg = palette.selection },
  PmenuMatch = { fg = palette.primary, bold = true },
  PmenuMatchSel = { fg = palette.bright, bg = palette.selection, bold = true },
  PmenuSbar = { bg = palette.surface },
  PmenuThumb = { bg = palette.border },
  Visual = { fg = palette.bright, bg = palette.selection },
  VisualNOS = { link = "Visual" },
  Search = { link = "Visual" },
  IncSearch = { fg = palette.bright, bg = palette.selection, bold = true },
  CurSearch = { link = "IncSearch" },
  Yank = { link = "Visual" },
  MatchParen = { fg = palette.bright, bg = palette.surface, bold = true, underline = true },
  NonText = { fg = palette.muted },
  SpecialKey = { link = "NonText" },
  Whitespace = { link = "NonText" },
  EndOfBuffer = { fg = palette.border },
  Directory = { fg = palette.tertiary },
  Title = { fg = palette.primary, bold = true },
  Comment = { fg = palette.muted, italic = true },
  Identifier = { fg = palette.text },
  Constant = { fg = palette.secondary },
  String = { link = "Constant" },
  Number = { link = "Constant" },
  Boolean = { link = "Constant" },
  Character = { link = "Constant" },
  Float = { link = "Constant" },
  Function = { fg = palette.quaternary },
  Statement = { fg = palette.primary },
  Keyword = { link = "Statement" },
  PreProc = { link = "Statement" },
  Type = { fg = palette.tertiary },
  Special = { fg = palette.subtle },
  Delimiter = { link = "Special" },
  Operator = { link = "Special" },
  Underlined = { fg = palette.primary, underline = true },
  Todo = { fg = palette.warning, bold = true },
  Error = { fg = palette.error },
  ErrorMsg = { link = "Error" },
  WarningMsg = { fg = palette.warning },
  MoreMsg = { fg = palette.primary },
  Question = { fg = palette.primary },
  WildMenu = { link = "PmenuSel" },
  DiffAdd = { fg = palette.success, bg = palette.container },
  DiffDelete = { fg = palette.error, bg = palette.container },
  DiffChange = { fg = palette.warning, bg = palette.container },
  DiffText = { fg = palette.bright, bg = palette.selection, bold = true },
  Added = { fg = palette.success },
  Removed = { fg = palette.error },
  Changed = { fg = palette.warning },
  DiagnosticError = { fg = palette.error },
  DiagnosticWarn = { fg = palette.warning },
  DiagnosticInfo = { fg = palette.info },
  DiagnosticHint = { fg = palette.secondary },
  DiagnosticOk = { fg = palette.success },
  DiagnosticUnderlineError = { sp = palette.error, undercurl = true },
  DiagnosticUnderlineWarn = { sp = palette.warning, undercurl = true },
  DiagnosticUnderlineInfo = { sp = palette.info, undercurl = true },
  DiagnosticUnderlineHint = { sp = palette.secondary, undercurl = true },
  DiagnosticDeprecated = { fg = palette.muted, strikethrough = true },
  DiagnosticUnnecessary = { fg = palette.muted },
  LspReferenceText = { bg = palette.surface, underline = true },
  LspReferenceRead = { link = "LspReferenceText" },
  LspReferenceWrite = { link = "LspReferenceText" },
  LspInlayHint = { fg = palette.muted, bg = palette.container },
  SpellBad = { sp = palette.error, undercurl = true },
  SpellCap = { sp = palette.warning, undercurl = true },
  SpellLocal = { sp = palette.info, undercurl = true },
  SpellRare = { sp = palette.secondary, undercurl = true },
  ["@variable"] = { link = "Identifier" },
  ["@variable.builtin"] = { link = "Identifier" },
  ["@variable.parameter"] = { link = "Identifier" },
  ["@variable.member"] = { link = "Identifier" },
  ["@module"] = { link = "Type" },
  ["@type"] = { link = "Type" },
  ["@function"] = { link = "Function" },
  ["@function.builtin"] = { link = "Function" },
  ["@constructor"] = { link = "Type" },
  ["@keyword"] = { link = "Statement" },
  ["@constant"] = { link = "Constant" },
  ["@string"] = { link = "String" },
  ["@number"] = { link = "Number" },
  ["@boolean"] = { link = "Boolean" },
  ["@property"] = { link = "Identifier" },
  ["@punctuation"] = { link = "Delimiter" },
  ["@operator"] = { link = "Operator" },
  ["@comment"] = { link = "Comment" },
  ["@comment.error"] = { link = "DiagnosticError" },
  ["@comment.warning"] = { link = "DiagnosticWarn" },
  ["@comment.todo"] = { link = "Todo" },
  ["@comment.note"] = { link = "DiagnosticInfo" },
  ["@tag"] = { link = "Statement" },
  ["@tag.attribute"] = { link = "Identifier" },
  ["@tag.delimiter"] = { link = "Delimiter" },
  ["@markup.heading"] = { link = "Title" },
  ["@markup.link"] = { link = "Underlined" },
  ["@markup.raw"] = { link = "String" },
  ["@markup.list"] = { link = "Delimiter" },
  ["@markup.strong"] = { bold = true },
  ["@markup.italic"] = { italic = true },
}

for name, attributes in pairs(groups) do
  vim.api.nvim_set_hl(0, name, attributes)
end

local ansi = {
  "#887E78", "#E07972", "#9E8F85", "#B4A094",
  "#C9B2A3", "#DBC6B8", "#EBDACF", "#F3E9E2",
  "#A1968F", "#FF8A83", "#B3A195", "#C8B3A4",
  "#DEC5B5", "#F0D9CA", "#FAE7DB", "#FCF3EE",
}

for index, color in ipairs(ansi) do
  vim.g["terminal_color_" .. (index - 1)] = color
end
