# Path
export PATH="$PATH:$HOME/.local/bin:$HOME/.composer/vendor/bin:$HOME/.spicetify:$HOME/.pyenv/bin:$HOME/.bun/bin:$HOME/.local/share/JetBrains/Toolbox/scripts:"

# Path to OMZ installation.
export ZSH="$HOME/.oh-my-zsh"

# Editor env variables
export EDITOR=nvim
export SUDO_EDITOR=nvim
export MANPAGE="less -R --use-color -Dd+r -Du+b"

# Theme
ZSH_THEME="refined"

# Plugins
plugins=(cp fast-syntax-highlighting fzf git poetry ruby ubuntu zsh-autosuggestions)

# OMZ script
source $ZSH/oh-my-zsh.sh

# Aliases
alias ls="eza --color=always --icons --group-directories-first"
alias la="eza -lah --color=always --icons --group-directories-first"
alias lt="eza -aT --color=always --icons --group-directories-first"
alias lh="eza -la --color=always --icons --group-directories-first | grep '^\.'"
alias as="apt search"
alias cp="cpv"
alias ar="php artisan"
alias rm="trash"
alias c="clear"
alias fzf="fzf --style full"
alias dir="cd ~ && cd \$(find * -type d | fzf)"
alias ff="fastfetch"
alias vim="nvim"

# GPG stuff
export GPG_TTY=$(tty)

# bun completions
[ -s "/home/aileks/.bun/_bun" ] && source "/home/aileks/.bun/_bun"

# pyenv
export PYENV_ROOT="$HOME/.pyenv"
[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"
export PIPENV_VENV_IN_PROJECT=1

# Zoxide
eval "$(zoxide init zsh)"

# fzf plugin config
export FZF_CTRL_T_OPTS="
  --walker-skip .git,node_modules,target
  --preview 'bat -n --color=always {}'
  --bind 'ctrl-/:change-preview-window(down|hidden|)'"
export FZF_ALT_C_OPTS="
  --walker-skip .git,node_modules,target
  --preview 'tree -C {}'"

# nvm
export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

export PATH=$PATH:/home/aileks/.spicetify
