/*
 * DWM-Flexipatch patches configuration
 * Ashen colorscheme dotfiles
 *
 * Enable patches by setting value to 1
 */

/**
 * Bar modules
 */

#define BAR_AWESOMEBAR_PATCH 0
#define BAR_DWMBLOCKS_PATCH 1
#define BAR_DWMBLOCKS_SIGUSR1_PATCH 1
#define BAR_FANCYBAR_PATCH 0
#define BAR_FLEXWINTITLE_PATCH 0
#define BAR_LAUNCHER_PATCH 0
#define BAR_LAYOUTMENU_PATCH 0
#define BAR_LTSYMBOL_PATCH 1
#define BAR_LTSYMBOL_SCHEME_PATCH 0
#define BAR_POWERLINE_STATUS_PATCH 0
#define BAR_POWERLINE_TAGS_PATCH 0
#define BAR_POWERLINE_TAGS_SLASH_PATCH 0
#define BAR_TABGROUPS_PATCH 0
#define BAR_TAGGRID_PATCH 0
#define BAR_TAGPREVIEW_PATCH 0
#define BAR_STATUS_PATCH 1
#define BAR_STATUSBUTTON_PATCH 0
#define BAR_STATUSCMD_PATCH 1
#define BAR_STATUS2D_PATCH 1
#define BAR_STATUS2D_NO_ALPHA_PATCH 0
#define BAR_STATUS2D_XRDB_TERMCOLORS_PATCH 0
#define BAR_SYSTRAY_PATCH 1
#define BAR_TAGS_PATCH 1
#define BAR_TAGLABELS_PATCH 0
#define BAR_UNDERLINETAGS_PATCH 0
#define BAR_WINICON_PATCH 0
#define BAR_WINTITLE_PATCH 1
#define BAR_WINTITLE_FLOATING_PATCH 0
#define BAR_WINTITLE_HIDDEN_PATCH 0
#define BAR_TITLE_RIGHT_PAD_PATCH 0
#define BAR_TITLE_LEFT_PAD_PATCH 0

/**
 * Bar options
 */

#define BAR_ALPHA_PATCH 1
#define BAR_ALTERNATIVE_TAGS_PATCH 0
#define BAR_ALTTAGSDECORATION_PATCH 0
#define BAR_ANYBAR_PATCH 0
#define BAR_ANYBAR_TOP_AND_BOTTOM_BARS_PATCH 0
#define BAR_ANYBAR_MANAGE_WIDTH_PATCH 0
#define BAR_BORDER_PATCH 0
#define BAR_BORDER_COLBG_PATCH 0
#define BAR_CENTEREDWINDOWNAME_PATCH 0
#define BAR_DMENUMATCHTOP_PATCH 1
#define BAR_EXTRASTATUS_PATCH 0
#define BAR_EWMHTAGS_PATCH 1
#define BAR_HEIGHT_PATCH 1
#define BAR_HIDEVACANTTAGS_PATCH 0
#define BAR_HOLDBAR_PATCH 0
#define BAR_IGNORE_XFT_ERRORS_WHEN_DRAWING_TEXT_PATCH 1
#define BAR_NO_COLOR_EMOJI_PATCH 0
#define BAR_PADDING_PATCH 0
#define BAR_PADDING_VANITYGAPS_PATCH 0
#define BAR_PADDING_SMART_PATCH 0
#define BAR_PANGO_PATCH 1
#define BAR_STATICSTATUS_PATCH 0
#define BAR_STATUSALLMONS_PATCH 0
#define BAR_STATUSCOLORS_PATCH 0
#define BAR_STATUSPADDING_PATCH 1
#define BAR_VTCOLORS_PATCH 0
#define BAR_WINTITLEACTIONS_PATCH 0

/**
 * Other patches
 */

#define ALT_TAB_PATCH 0
#define ALWAYSCENTER_PATCH 1
#define ALWAYSONTOP_PATCH 0
#define ASPECTRESIZE_PATCH 0
#define ATTACHABOVE_PATCH 0
#define ATTACHASIDE_PATCH 0
#define ATTACHBELOW_PATCH 1
#define ATTACHBOTTOM_PATCH 0
#define AUTOSTART_PATCH 0
#define AUTORESIZE_PATCH 0
#define BANISH_PATCH 0
#define BIDI_PATCH 0
#define BORDER_RULE_PATCH 0
#define CENTER_PATCH 0
#define CENTER_TRANSIENT_WINDOWS_PATCH 0
#define CENTER_TRANSIENT_WINDOWS_BY_PARENT_PATCH 0
#define CFACTS_PATCH 1
#define CMDCUSTOMIZE_PATCH 0
#define COMBO_PATCH 0
#define COOL_AUTOSTART_PATCH 0
#define CYCLELAYOUTS_PATCH 1
#define DECORATION_HINTS_PATCH 0
#define DISTRIBUTETAGS_PATCH 0
#define DO_NOT_DIE_ON_COLOR_ALLOCATION_FAILURE_PATCH 1
#define DRAGCFACT_PATCH 0
#define DRAGMFACT_PATCH 0
#define DWMC_PATCH 0
#define EMPTYVIEW_PATCH 0
#define EXRESIZE_PATCH 0
#define FAKEFULLSCREEN_PATCH 0
#define FAKEFULLSCREEN_CLIENT_PATCH 0
#define FLOATPOS_PATCH 0
#define FLOATPOS_RESPECT_GAPS_PATCH 0
#define FOCUSADJACENTTAG_PATCH 0
#define FOCUSDIR_PATCH 0
#define FOCUSFOLLOWMOUSE_PATCH 0
#define FOCUSMASTER_PATCH 0
#define FOCUSMASTER_RETURN_PATCH 0
#define FOCUSONCLICK_PATCH 0
#define FOCUSURGENT_PATCH 1
#define FOCUSONNETACTIVE_PATCH 0
#define FSIGNAL_PATCH 0
#define FULLSCREEN_PATCH 1
#define GAMES_PATCH 0
#define INPLACEROTATE_PATCH 0
#define INSETS_PATCH 0
#define IPC_PATCH 0
#define ISPERMANENT_PATCH 0
#define KEYMODES_PATCH 0
#define KILLUNSEL_PATCH 0
#define LG3D_PATCH 0
#define LOSEFULLSCREEN_PATCH 1
#define MAXIMIZE_PATCH 0
#define MPDCONTROL_PATCH 0
#define MONITOR_RULES_PATCH 0
#define MONOCLESYMBOL_PATCH 0
#define MOVECENTER_PATCH 1
#define MOVEPLACE_PATCH 0
#define MOVERESIZE_PATCH 0
#define MOVESTACK_PATCH 1
#define NAMETAG_PATCH 0
#define NAMETAG_PREPEND_PATCH 0
#define NET_CLIENT_LIST_STACKING_PATCH 0
#define NOBORDER_PATCH 1
#define NODMENU_PATCH 0
#define NO_MOD_BUTTONS_PATCH 0
#define NO_TRANSPARENT_BORDERS_PATCH 0
#define ON_EMPTY_KEYS_PATCH 0
#define ONLY_ONE_RULE_MATCH_PATCH 0
#define ONLYQUITONEMPTY_PATCH 0
#define PERTAG_PATCH 1
#define PERTAG_VANITYGAPS_PATCH 0
#define PERMON_VANITYGAPS_PATCH 0
#define PERTAGBAR_PATCH 0
#define PLACEDIR_PATCH 0
#define PLACEMOUSE_PATCH 0
#define PUSH_PATCH 0
#define PUSH_NO_MASTER_PATCH 0
#define RENAMED_SCRATCHPADS_PATCH 0
#define RENAMED_SCRATCHPADS_AUTO_HIDE_PATCH 0
#define REORGANIZETAGS_PATCH 0
#define RESIZECORNERS_PATCH 0
#define RESIZEPOINT_PATCH 0
#define RESTARTSIG_PATCH 1
#define RIODRAW_PATCH 0
#define ROTATESTACK_PATCH 0
#define ROUNDED_CORNERS_PATCH 0
#define SAVEFLOATS_PATCH 1
#define SCRATCHPADS_PATCH 1
#define SCRATCHPADS_KEEP_POSITION_AND_SIZE_PATCH 1
#define SCRATCHPAD_ALT_1_PATCH 0
#define SEAMLESS_RESTART_PATCH 0
#define SELECTIVEFAKEFULLSCREEN_PATCH 0
#define SELFRESTART_PATCH 1
#define SENDMON_CENTER_PATCH 0
#define SENDMON_KEEPFOCUS_PATCH 0
#define SETBORDERPX_PATCH 0
#define SHIFTBOTH_PATCH 0
#define SHIFTSWAPTAGS_PATCH 0
#define SHIFTTAG_PATCH 0
#define SHIFTTAGCLIENTS_PATCH 0
#define SHIFTVIEW_PATCH 0
#define SHIFTVIEW_CLIENTS_PATCH 0
#define SIZEHINTS_PATCH 0
#define SIZEHINTS_RULED_PATCH 0
#define SIZEHINTS_ISFREESIZE_PATCH 0
#define SORTSCREENS_PATCH 0
#define SPAWNCMD_PATCH 0
#define STACKER_PATCH 0
#define STEAM_PATCH 0
#define STICKY_PATCH 1
#define SWALLOW_PATCH 0
#define SWAPFOCUS_PATCH 0
#define SWAPTAGS_PATCH 0
#define SWITCHCOL_PATCH 0
#define TAB_PATCH 0
#define TAGALL_PATCH 0
#define TAGALLMON_PATCH 0
#define TAGOTHERMONITOR_PATCH 0
#define TAGSWAPMON_PATCH 0
#define TAPRESIZE_PATCH 0
#define TOGGLEFULLSCREEN_PATCH 1
#define TOGGLETOPBAR_PATCH 0
#define TRANSFER_PATCH 0
#define TRANSFER_ALL_PATCH 0
#define UNFLOATVISIBLE_PATCH 0
#define VANITYGAPS_PATCH 1
#define VANITYGAPS_MONOCLE_PATCH 0
#define WARP_PATCH 0
#define WINVIEW_PATCH 0
#define XKB_PATCH 0
#define XRDB_PATCH 0
#define XRESOURCES_PATCH 0
#define ZOOMSWAP_PATCH 0

/**
 * Layouts
 */

#define BSTACK_LAYOUT 1
#define BSTACKHORIZ_LAYOUT 1
#define CENTEREDMASTER_LAYOUT 1
#define CENTEREDFLOATINGMASTER_LAYOUT 0
#define COLUMNS_LAYOUT 0
#define DECK_LAYOUT 1
#define FIBONACCI_DWINDLE_LAYOUT 1
#define FIBONACCI_SPIRAL_LAYOUT 1
#define FLEXTILE_DELUXE_LAYOUT 1
#define GAPPLESSGRID_LAYOUT 0
#define GRIDMODE_LAYOUT 0
#define HORIZGRID_LAYOUT 0
#define MONOCLE_LAYOUT 1
#define NROWGRID_LAYOUT 0
#define TILE_LAYOUT 1
