[[mgr.prepend_keymap]]
desc = "Bookmarks and mounted drives"
on = ["g", "b"]
run = "shell -- file-locations"

[[mgr.prepend_keymap]]
desc = "Trash selected files"
on = "D"
run = "remove"

[[mgr.prepend_keymap]]
desc = "Trash selected files"
on = "<Delete>"
run = "remove"

[[mgr.prepend_keymap]]
desc = "Edit selected files"
on = "e"
run = "shell --block -- nvim -- %s"
