[mgr]
linemode = "size"
scrolloff = 3
show_hidden = true
show_symlink = true
sort_by = "natural"
sort_dir_first = true
sort_sensitive = false

[[open.prepend_rules]]
mime = "application/{xml,*+xml,*+json,toml,yaml,x-yaml,x-shellscript}"
use = ["edit", "reveal"]

[[opener.edit]]
block = true
desc = "Neovim"
for = "unix"
run = "nvim -- %s"

[[opener.open]]
desc = "Open"
for = "linux"
orphan = true
run = "xdg-open %s1"

[[opener.play]]
desc = "mpv"
for = "linux"
orphan = true
run = "mpv -- %s"

[[opener.reveal]]
desc = "Show in PCManFM"
for = "linux"
orphan = true
run = "pcmanfm %d1"
