SSH_AUTH_SOCK=${HOME}/.bitwarden-ssh-agent.sock
NVD_BACKEND=direct
LIBVA_DRIVER_NAME=nvidia
__GLX_VENDOR_LIBRARY_NAME=nvidia
ELECTRON_OZONE_PLATFORM_HINT=auto
GDK_BACKEND=wayland,x11
QT_QPA_PLATFORM=wayland;xcb
QT_QPA_PLATFORMTHEME=qt6ct
SDL_VIDEODRIVER=wayland
CLUTTER_BACKEND=wayland
XCURSOR_THEME=Adwaita
XCURSOR_SIZE=24
HYPRCURSOR_THEME=Adwaita
HYPRCURSOR_SIZE=24
