theme = "dracula"

[editor]
line-number = "relative"
mouse = false
bufferline = "multiple"
auto-save = true
idle-timeout = 300

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
left = ["mode", "spinner", "version-control", "file-encoding"]
center = ["file-name", "file-modification-indicator"]
right = ["diagnostics", "position", "file-encoding", "total-line-numbers", "file-type"]
separator = "│"
mode.normal = "NOR"
mode.insert = "INS"
mode.select = "SEL"

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.indent-guides]
render = true
character = "┆"
skip-levels = 1

[editor.gutters.line-numbers]
min-width = 1

[editor.soft-wrap]
enable = true
max-wrap = 25
max-indent-retain = 0
