use-grammars = { only = ["rust", "c", "cpp", "java" ] }

[[language]]
name = "rust"
auto-format = true
scope = "source.rust"
injection-regex = "rust"
indent = { tab-width = 4, unit = "    " }
formatter = { command = "rustfmt" }

[language-server.rust-analyzer.config.check]
command = "clippy"

[[language]]
name = "java"
language-server = { command = "jdtls" }
scope = "source.java"
injection-regex = "java"
