;;; -*- lexical-binding: t -*-

;; Define Ashen theme
(deftheme ashen "Ashen color scheme")

(let ((dark-background "#121212")
      (dark-gray "#191919")
      (selection-gray "#212121")
      (comment-gray "#535353")
      (mid-gray "#949494")
      (foreground "#a7a7a7")
      (light-foreground "#b4b4b4")
      (light-background "#d5d5d5")
      (red-ember "#b14242")
      (blue "#4a8b8b")
      (orange-blaze "#c4693d")
      (red-glowing "#df6464")
      (orange-smolder "#e49a44")
      (orange-glow "#d87c4a")
      (brown "#89492a"))

  (custom-theme-set-faces
   'ashen
   `(default ((t (:foreground ,foreground :background ,dark-background))))
   `(cursor ((t (:background ,red-ember))))
   `(fringe ((t (:background ,dark-gray))))
   `(region ((t (:background ,selection-gray))))
   `(highlight ((t (:background ,dark-gray))))
   `(font-lock-builtin-face ((t (:foreground ,orange-smolder))))
   `(font-lock-comment-face ((t (:foreground ,comment-gray))))
   `(font-lock-constant-face ((t (:foreground ,red-ember))))
   `(font-lock-function-name-face ((t (:foreground ,orange-glow))))
   `(font-lock-keyword-face ((t (:foreground ,red-ember))))
   `(font-lock-string-face ((t (:foreground ,red-glowing))))
   `(font-lock-type-face ((t (:foreground ,orange-blaze))))
   `(font-lock-variable-name-face ((t (:foreground ,blue))))
   `(mode-line ((t (:foreground ,foreground :background ,selection-gray))))
   `(mode-line-inactive ((t (:foreground ,comment-gray :background ,dark-gray))))
   `(line-number ((t (:foreground ,comment-gray :background ,dark-gray))))
   `(line-number-current-line ((t (:foreground ,foreground :background ,selection-gray))))
   `(dired-directory ((t (:foreground ,orange-glow))))
   `(dired-symlink ((t (:foreground ,red-ember))))
   `(dired-ignored ((t (:foreground ,comment-gray))))
   `(org-level-1 ((t (:foreground ,blue :weight bold))))
   `(org-level-2 ((t (:foreground ,orange-blaze))))
   `(org-level-3 ((t (:foreground ,orange-glow))))
   `(org-block ((t (:background ,dark-gray))))
   `(org-code ((t (:foreground ,orange-blaze))))
   `(error ((t (:foreground ,red-ember :weight bold))))
   `(warning ((t (:foreground ,blue :weight bold))))
   `(success ((t (:foreground ,red-glowing :weight bold))))
   `(isearch ((t (:foreground ,orange-blaze :background ,dark-gray :inverse-video t))))
   `(lazy-highlight ((t (:foreground ,orange-smolder :background ,dark-gray :inverse-video t))))
   `(link ((t (:foreground ,orange-glow :underline t))))
   `(link-visited ((t (:foreground ,red-ember :underline t))))))

(provide-theme 'ashen)
